# Form implementation generated from reading ui file 'Proyecto2.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import Text
from PyQt6 import QtCore, QtGui, QtWidgets
import os
import core
import data
import numpy as np
from time import sleep
from PIL import Image, ImageQt

class Ui_MainWindow(object):

    cursorArray = []
    position = 0
    totalResults = 0

    pathImage = ''
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 618)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setVisible(False)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 1001, 591))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 35, 490, 550))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(2, 30, 486, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.img_label = QtWidgets.QLabel(self.frame)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(350, 512, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.processImage)
        self.pushButton.setEnabled(False)

        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setGeometry(QtCore.QRect(500, 35, 490, 550))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 471, 481))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.formLayout.setContentsMargins(15, 45, 15, 0)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_6)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 510, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.saveData)
        self.pushButton_2.setEnabled(False)


        #Creating home page
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1010, 600))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
       
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(118, 280, 180, 180))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(((os.path.dirname(os.path.realpath(__file__))+"\\resources\\OCRicon.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.showMainPage)
        self.pushButton_3.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(415, 280, 180, 180))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(((os.path.dirname(os.path.realpath(__file__))+"\\resources\\searchIcon.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        self.pushButton_4.clicked.connect(self.showSearchPage)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(712, 280, 180, 180))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(((os.path.dirname(os.path.realpath(__file__))+"\\resources\\infoIcon.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        self.pushButton_5.clicked.connect(self.helpPage)
        #Adding background
        self.label_Background = QtWidgets.QLabel(self.frame_3)
        self.label_Background.setGeometry(QtCore.QRect(0, 0, 1010, 600))
        self.label_Background.setText("")
        self.label_Background.setPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\homePage.png")))
        self.label_Background.setObjectName("label_Background")
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        #Creating top bar
        self.pushButton_New = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_New.setGeometry(QtCore.QRect(50, 0, 45, 40))
        self.pushButton_New.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\newIcon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_New.setIcon(icon)
        self.pushButton_New.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_New.setObjectName("pushButton_New")
        self.pushButton_New.setVisible(False)
        self.pushButton_New.clicked.connect(self.newImage)
        self.pushButton_New.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(47, 227, 194);""}")
        self.pushButton_Home = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Home.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.pushButton_Home.setText("")
        self.pushButton_Home.clicked.connect(self.showHomePage)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\homeIcon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Home.setIcon(icon1)
        self.pushButton_Home.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton_Home.setVisible(False)
        self.pushButton_Home.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(47, 227, 194);""}")
        
        self.pushButton_Settings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Settings.setGeometry(QtCore.QRect(969, 0, 40, 40))
        self.pushButton_Settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\settingsIcon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Settings.setIcon(icon2)
        self.pushButton_Settings.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.pushButton_Settings.setVisible(False)
        self.pushButton_Settings.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(47, 227, 194);""}")
        self.pushButton_Settings.clicked.connect(self.changeCI)

        #Creating search page
        self.frame_search = QtWidgets.QFrame(self.centralwidget)
        self.frame_search.setEnabled(True)
        self.frame_search.setGeometry(QtCore.QRect(15, 45, 1001, 591))
        self.frame_search.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_search.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_search.setObjectName("frame_search")
        self.groupBox_search = QtWidgets.QGroupBox(self.frame_search)
        self.groupBox_search.setGeometry(QtCore.QRect(0, 0, 490, 551))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_search.setFont(font)
        self.groupBox_search.setObjectName("groupBox_search")
        self.pushButton_search = QtWidgets.QPushButton(self.groupBox_search)
        self.pushButton_search.setGeometry(QtCore.QRect(350, 120, 131, 31))
        self.pushButton_search.setObjectName("pushButton_search")
        self.pushButton_search.clicked.connect(self.searchUser)
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_search)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 200, 471, 316))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_search = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_search.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.formLayout_search.setContentsMargins(15, 45, 15, 0)
        self.formLayout_search.setVerticalSpacing(25)
        self.formLayout_search.setObjectName("formLayout_search")
        self.label_search1 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_search1.setFont(font)
        self.label_search1.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_search1.setObjectName("label_search1")
        self.formLayout_search.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_search1)
        self.label_result1 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result1.setFont(font)
        self.label_result1.setText("")
        self.label_result1.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_result1.setObjectName("label_result1")
        self.formLayout_search.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_result1)
        self.label_search2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_search2.setFont(font)
        self.label_search2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_search2.setObjectName("label_search2")
        self.formLayout_search.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_search2)
        self.label_search3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_search3.setFont(font)
        self.label_search3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_search3.setObjectName("label_search3")
        self.formLayout_search.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_search3)
        self.label_search4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_search4.setFont(font)
        self.label_search4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_search4.setObjectName("label_search4")
        self.formLayout_search.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_search4)
        self.label_result2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result2.setFont(font)
        self.label_result2.setText("")
        self.label_result2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_result2.setObjectName("label_result2")
        self.formLayout_search.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_result2)
        self.label_result3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result3.setFont(font)
        self.label_result3.setText("")
        self.label_result3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_result3.setObjectName("label_result3")
        self.formLayout_search.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_result3)
        self.label_result4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result4.setFont(font)
        self.label_result4.setText("")
        self.label_result4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_result4.setObjectName("label_result4")
        self.formLayout_search.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_result4)
        self.label_search5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_search5.setFont(font)
        self.label_search5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_search5.setObjectName("label_search5")
        self.formLayout_search.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_search5)
        self.label_search6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_search6.setFont(font)
        self.label_search6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_search6.setObjectName("label_search6")
        self.formLayout_search.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_search6)
        self.label_result5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result5.setFont(font)
        self.label_result5.setText("")
        self.label_result5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_result5.setObjectName("label_result5")
        self.formLayout_search.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_result5)
        self.label_result6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result6.setFont(font)
        self.label_result6.setText("")
        self.label_result6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_result6.setObjectName("label_result6")
        self.formLayout_search.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_result6)
        self.lineEdit_filter = QtWidgets.QLineEdit(self.groupBox_search)
        self.lineEdit_filter.setGeometry(QtCore.QRect(188, 30, 291, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_filter.setFont(font)
        self.lineEdit_filter.setObjectName("lineEdit_filter")
        self.pushButton_next = QtWidgets.QPushButton(self.groupBox_search)
        self.pushButton_next.setGeometry(QtCore.QRect(350, 520, 131, 31))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_next.setDisabled(True)
        self.pushButton_next.clicked.connect(self.nextResult)
        self.label_results = QtWidgets.QLabel(self.groupBox_search)
        self.label_results.setGeometry(QtCore.QRect(10, 160, 451, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_results.setFont(font)
        self.label_results.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_results.setObjectName("label_results")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_search)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 170, 24))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.activated.connect(self.format)
        self.label_format = QtWidgets.QLabel(self.groupBox_search)
        self.label_format.setGeometry(QtCore.QRect(340, 50, 170, 24))
        self.label_format.setFont(font)
        self.label_format.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_format.setObjectName("label_format")
        self.label_format.setText('Format: 28FEB1990')
        self.label_format.setVisible(False)
        self.pushButton_previous = QtWidgets.QPushButton(self.groupBox_search)
        self.pushButton_previous.setGeometry(QtCore.QRect(10, 520, 131, 31))
        self.pushButton_previous.setObjectName("pushButton_previous")
        self.pushButton_previous.setDisabled(True)
        self.pushButton_previous.clicked.connect(self.prevResult)
        self.groupBox_image = QtWidgets.QGroupBox(self.frame_search)
        self.groupBox_image.setGeometry(QtCore.QRect(490, 0, 490, 551))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_image.setFont(font)
        self.groupBox_image.setObjectName("groupBox_image")
        self.frame_search1 = QtWidgets.QFrame(self.groupBox_image)
        self.frame_search1.setGeometry(QtCore.QRect(10, 30, 471, 521))
        self.frame_search1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_search1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_search1.setObjectName("frame_search1")
        self.frame_search.setVisible(False)
        self.img_labelSearch = QtWidgets.QLabel(self.frame_search1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_search)
        self.radioButton.setGeometry(QtCore.QRect(190, 85, 111, 18))
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setChecked(True)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_search)
        self.radioButton_2.setGeometry(QtCore.QRect(340, 85, 131, 18))
        self.radioButton_2.setObjectName("radioButton_2")

         #Creating help page
        self.frame_help = QtWidgets.QFrame(self.centralwidget)
        self.frame_help.setGeometry(QtCore.QRect(0, 0, 1010, 600))
        self.frame_help.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_help.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_help.setObjectName("frame_help")
        #Adding background to help page
        self.label_help = QtWidgets.QLabel(self.frame_help)
        self.label_help.setGeometry(QtCore.QRect(0, 40, 1010, 600))
        self.label_help.setText("")
        self.label_help.setPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\helpPage.png")))
        self.label_help.setObjectName("label_help")
        self.frame_help.setVisible(False)


        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtGui.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSearch_info = QtGui.QAction(MainWindow)
        self.actionSearch_info.setObjectName("actionSearch_info")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        try:
            data.searchTable()
        except Exception as e:
           qm = QtWidgets.QMessageBox
           qm.critical(self.centralwidget,"Error", "An error has occurred, could not load the database." + '\nError code: ' + str(e), qm.StandardButton.Close, qm.StandardButton.Close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ID Reader"))
        self.groupBox.setTitle(_translate("MainWindow", "Image"))
        self.pushButton.setText(_translate("MainWindow", "Process Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Data extracted"))
        self.label.setText(_translate("MainWindow", "ID Number:"))
        self.label_2.setText(_translate("MainWindow", "Names:"))
        self.label_3.setText(_translate("MainWindow", "Family Names:"))
        self.label_4.setText(_translate("MainWindow", "Gender:"))
        self.label_5.setText(_translate("MainWindow", "Nationality:"))
        self.label_6.setText(_translate("MainWindow", "Date of Birth:"))
        self.pushButton_2.setText(_translate("MainWindow", "Save Data"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open image"))
        self.actionSearch_info.setText(_translate("MainWindow", "Search info"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open image"))
        self.actionSearch_info.setText(_translate("MainWindow", "Search info"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.groupBox_search.setTitle(_translate("MainWindow", "Filters"))
        self.pushButton_search.setText(_translate("MainWindow", "Search"))
        self.label_search1.setText(_translate("MainWindow", "ID Number:"))
        self.label_search2.setText(_translate("MainWindow", "Names:"))
        self.label_search3.setText(_translate("MainWindow", "Surnames:"))
        self.label_search4.setText(_translate("MainWindow", "Gender:"))
        self.label_search5.setText(_translate("MainWindow", "Nationality:"))
        self.label_search6.setText(_translate("MainWindow", "Date of Birth:"))
        self.pushButton_next.setText(_translate("MainWindow", "Next"))
        self.label_results.setText(_translate("MainWindow", "Results: "))
        self.comboBox.setItemText(0, _translate("MainWindow", "ID Number"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Names"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Surnames"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Gender"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Nationality"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Date of Birth"))
        self.pushButton_previous.setText(_translate("MainWindow", "Previous"))
        self.groupBox_image.setTitle(_translate("MainWindow", "Image"))
        self.radioButton.setText(_translate("MainWindow", "Exact match"))
        self.radioButton_2.setText(_translate("MainWindow", "Partial match"))


    #Function to show the main page
    def showMainPage(self):
        self.frame_3.setVisible(False)
        self.frame_2.setVisible(True)
        self.frame.setVisible(True)
        self.img_label.setVisible(True)
        self.pushButton_Home.setVisible(True)
        self.pushButton_New.setVisible(True)
        self.pushButton_Settings.setVisible(True)

    #Function to show the help page
    def helpPage(self):
        self.frame_3.setVisible(False)
        self.frame_2.setVisible(False)
        self.frame.setVisible(False)
        self.img_label.setVisible(False)
        self.pushButton_Home.setVisible(False)
        self.pushButton_New.setVisible(False)
        self.pushButton_Settings.setVisible(False)
        self.frame_help.setVisible(True)
        self.pushButton_Home.setVisible(True)
        self.pushButton_Home.raise_()
        self.pushButton_Home.setEnabled(True)

    #Function to open a file
    def getfile(self):
        try:
            fDialog = QtWidgets.QFileDialog()
            file_filter = 'Image File (*.jpg *.jpeg *.png)'
            fname = fDialog.getOpenFileName(caption='Select a data file', filter=file_filter,)
            if fname[0] != "":
                self.frame_3.setVisible(False)
                
                self.pathImage = fname[0]
                pixmap = QtGui.QPixmap(self.pathImage)

                if pixmap.isNull():
                    self.img_label.clear()
                    self.img_label.setText('Image too large to preview. Please proceed to process the image.')
                    self.img_label.resize(480,30)
                    self.pushButton.setEnabled(True)
                else:
                    self.img_label.clear()
                    pixmap = pixmap.scaled(480, 480, QtCore.Qt.AspectRatioMode.KeepAspectRatio)
                    self.img_label.setPixmap(pixmap)
                    self.img_label.setScaledContents(True)
                    self.img_label.resize(pixmap.width(),pixmap.height())
                    self.pushButton.setEnabled(True)
                self.showMainPage()
        except Exception as e:
            qm = QtWidgets.QMessageBox
            qm.critical(self.centralwidget,"Error", "An error has occurred, could not load the image." + '\nError code: ' + str(e), qm.StandardButton.Close, qm.StandardButton.Close)
    
    #Function to process the image
    def processImage(self):
        #Initialze QtGui.QImage() with arguments data, height, width, and QImage.Format
        imgResults = core.processImage(self.pathImage)
        
        #Review if the process finished
        if imgResults[0]:
            pixmap = QtGui.QPixmap(imgResults[1])
            pixmap = pixmap.scaled(480, 480, QtCore.Qt.AspectRatioMode.KeepAspectRatio)
            self.img_label.setPixmap(pixmap)
            self.img_label.setScaledContents(True)
            self.img_label.resize(pixmap.width(),pixmap.height())

            self.lineEdit.setText(imgResults[2][0][1])
            if imgResults[2][0][2] < core.minCI:
                self.lineEdit.setStyleSheet("color: red;")
            
            else:
                self.lineEdit.setStyleSheet("color: green;")

            self.lineEdit_2.setText(imgResults[2][1][1])
            if imgResults[2][1][2] < core.minCI:
                self.lineEdit_2.setStyleSheet("color: red;")
            
            else:
                self.lineEdit_2.setStyleSheet("color: green;")

            self.lineEdit_3.setText(imgResults[2][2][1])
            if imgResults[2][2][2] < core.minCI:
                self.lineEdit_3.setStyleSheet("color: red;")

            else:
                self.lineEdit_3.setStyleSheet("color: green;")

            self.lineEdit_4.setText(imgResults[2][3][1])
            if imgResults[2][3][2] < core.minCI:
                self.lineEdit_4.setStyleSheet("color: red;")

            else:
                self.lineEdit_4.setStyleSheet("color: green;")

            self.lineEdit_5.setText(imgResults[2][4][1])
            if imgResults[2][4][2] < core.minCI:
                self.lineEdit_5.setStyleSheet("color: red;")

            else:
                self.lineEdit_5.setStyleSheet("color: green;")

            self.lineEdit_6.setText(imgResults[2][5][1])
            if imgResults[2][5][2] < core.minCI:
                self.lineEdit_6.setStyleSheet("color: red;")
            
            else:
                self.lineEdit_6.setStyleSheet("color: green;")

            self.frame_2.setVisible(True)
            self.pushButton_2.setEnabled(True)
            os.remove((os.path.dirname(os.path.realpath(__file__))+"\\tmp\\imageTmp.jpg"))
       
        
    #Function to get back home page
    def showHomePage(self):
        self.frame_2.setVisible(False)
        self.frame_search.setVisible(False)
        self.frame_3.setVisible(True)
        self.pushButton_Settings.setVisible(False)
        self.frame_help.setVisible(False)
        
        self.pushButton_Home.setVisible(False)
        self.pushButton_New.setVisible(False)
        self.pathImage = ''
        self.img_label.clear()
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        core.results = []
        core.processFinish = False

    #Function to open a new image
    def newImage(self):
        if self.pathImage != '':
            qm = QtWidgets.QMessageBox
            ans = qm.warning(self.centralwidget,"Warning", "When open a new image data not saved will be lost. Are you sure to continue?", qm.StandardButton.Yes | qm.StandardButton.No, qm.StandardButton.No)

            if ans == qm.StandardButton.Yes:
                self.pathImage = ''
                self.img_label.clear()
                self.lineEdit.clear()
                self.lineEdit_2.clear()
                self.lineEdit_3.clear()
                self.lineEdit_4.clear()
                self.lineEdit_5.clear()
                self.lineEdit_6.clear()
                self.pushButton_2.setEnabled(False)
                self.pushButton.setEnabled(False)
                core.results = []
                core.processFinish = False
                self.getfile()
        else:
            self.getfile()

    #Function to clean main page
    def newPage(self):
        self.pathImage = ''
        self.img_label.clear()
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        core.results = []
        core.processFinish = False
        self.pushButton_2.setEnabled(False)
        self.pushButton.setEnabled(False)


    def saveData(self):
        try:
            modifiedData = [self.lineEdit.text(), self.lineEdit_2.text(), self.lineEdit_3.text(), self.lineEdit_4.text(), self.lineEdit_5.text(), self.lineEdit_6.text(), self.pathImage]
            saved = data.saveUser(modifiedData)
            if(saved):
                qm = QtWidgets.QMessageBox
                reply = qm.information(self.centralwidget,"Success", "Data saved successfully!")
                if reply == qm.StandardButton.Ok:
                    self.newPage()
                else:
                    self.newPage()
                
            else:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "An error has occurred, could not save data.", qm.StandardButton.Close, qm.StandardButton.Close)

        except Exception as e:
           qm = QtWidgets.QMessageBox
           qm.critical(self.centralwidget,"Error", "An error has occurred, could not save data." + '\nError code: ' + str(e), qm.StandardButton.Close, qm.StandardButton.Close)

    
    #Show search page
    def showSearchPage(self):
        self.frame_3.setVisible(False)
        self.frame_2.setVisible(False)
        self.frame.setVisible(False)
        self.img_label.setVisible(False)
        self.pushButton_Home.setVisible(True)
        self.pushButton_New.setVisible(False)
        self.pushButton_Settings.setVisible(True)
        self.label_search1.setVisible(False)
        self.label_search2.setVisible(False)
        self.label_search3.setVisible(False)
        self.label_search4.setVisible(False)
        self.label_search5.setVisible(False)
        self.label_search6.setVisible(False)
        self.frame_search.setVisible(True)

        


    #Show query results in the search page
    def showResults(self, cursor):
        self.cursorArray = list(cursor)
        self.totalResults = len(self.cursorArray)
        self.position = 0
        self.label_results.setText(str(self.totalResults) + " Results.")
        self.pushButton_next.setDisabled(True)
        self.pushButton_previous.setDisabled(True)

        if self.totalResults == 0:
            self.label_result1.clear()
            self.label_result2.clear()
            self.label_result3.clear()
            self.label_result4.clear()
            self.label_result5.clear()
            self.label_result6.clear()
            self.img_labelSearch.clear()
            self.label_search1.setVisible(False)
            self.label_search2.setVisible(False)
            self.label_search3.setVisible(False)
            self.label_search4.setVisible(False)
            self.label_search5.setVisible(False)
            self.label_search6.setVisible(False)
            self.label_result1.setVisible(False)
            self.label_result2.setVisible(False)
            self.label_result3.setVisible(False)
            self.label_result4.setVisible(False)
            self.label_result5.setVisible(False)
            self.label_result6.setVisible(False)

        
        else:
            if self.totalResults > 1:
                self.pushButton_next.setEnabled(True)

            row = self.cursorArray[self.position]
            self.label_result1.setText(str(row[0]))
            self.label_result2.setText(row[1])
            self.label_result3.setText(row[2])
            self.label_result4.setText(row[3])
            self.label_result5.setText(row[4])
            self.label_result6.setText(row[5])
            self.label_search1.setVisible(True)
            self.label_search2.setVisible(True)
            self.label_search3.setVisible(True)
            self.label_search4.setVisible(True)
            self.label_search5.setVisible(True)
            self.label_search6.setVisible(True)
            self.label_result1.setVisible(True)
            self.label_result2.setVisible(True)
            self.label_result3.setVisible(True)
            self.label_result4.setVisible(True)
            self.label_result5.setVisible(True)
            self.label_result6.setVisible(True)

            try:
                fname = row[6]
                if fname != "":
                    pixmap = QtGui.QPixmap(fname)

                    if pixmap.isNull():
                        self.img_labelSearch.clear()
                        self.img_labelSearch.setText('Image too large to preview. Please see the image in: ' + fname)
                        self.img_labelSearch.resize(480,30)
                    
                    else:
                        self.img_labelSearch.clear()
                        pixmap = pixmap.scaled(480, 480, QtCore.Qt.AspectRatioMode.KeepAspectRatio)
                        self.img_labelSearch.setPixmap(pixmap)
                        self.img_labelSearch.setScaledContents(True)
                        self.img_labelSearch.resize(pixmap.width(),pixmap.height())
                    self.img_labelSearch.setVisible(True)
                    self.frame_search1.setVisible(True)
                    
            except Exception as e:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "An error has occurred, could not load the image." + '\nError code: ' + str(e), qm.StandardButton.Close, qm.StandardButton.Close)

    
    def nextResult(self):
        self.position = self.position+1

        if self.position < (self.totalResults-1):
            self.pushButton_next.setEnabled(True)
        else:
            self.pushButton_next.setDisabled(True)

        if self.position < self.totalResults:
            row = self.cursorArray[self.position]
            self.label_result1.setText(str(row[0]))
            self.label_result2.setText(row[1])
            self.label_result3.setText(row[2])
            self.label_result4.setText(row[3])
            self.label_result5.setText(row[4])
            self.label_result6.setText(row[5])
            self.label_search1.setVisible(True)
            self.label_search2.setVisible(True)
            self.label_search3.setVisible(True)
            self.label_search4.setVisible(True)
            self.label_search5.setVisible(True)
            self.label_search6.setVisible(True)
            self.label_result1.setVisible(True)
            self.label_result2.setVisible(True)
            self.label_result3.setVisible(True)
            self.label_result4.setVisible(True)
            self.label_result5.setVisible(True)
            self.label_result6.setVisible(True)
            self.pushButton_previous.setEnabled(True)

            try:
                fname = row[6]
                
                if fname != "":
                    pixmap = QtGui.QPixmap(fname)

                    if pixmap.isNull():
                        self.img_labelSearch.clear()
                        self.img_labelSearch.setText('Image too large to preview. Please see the image in: ' + fname)
                        self.img_labelSearch.resize(480,30)
                    
                    else:
                        self.img_labelSearch.clear()
                        pixmap = pixmap.scaled(480, 480, QtCore.Qt.AspectRatioMode.KeepAspectRatio)
                        self.img_labelSearch.setPixmap(pixmap)
                        self.img_labelSearch.setScaledContents(True)
                        self.img_labelSearch.resize(pixmap.width(),pixmap.height())
                    self.img_labelSearch.setVisible(True)
                    self.frame_search1.setVisible(True)
                    
            except Exception as e:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "An error has occurred, could not load the image." + '\nError code: ' + str(e), qm.StandardButton.Close, qm.StandardButton.Close)

    
    def prevResult(self):
        self.position = self.position-1
        if self.position <= 0:
            self.pushButton_previous.setEnabled(False)
        else:
            self.pushButton_previous.setEnabled(True)

        if self.position < self.totalResults:
            row = self.cursorArray[self.position]
            self.label_result1.setText(str(row[0]))
            self.label_result2.setText(row[1])
            self.label_result3.setText(row[2])
            self.label_result4.setText(row[3])
            self.label_result5.setText(row[4])
            self.label_result6.setText(row[5])
            self.label_search1.setVisible(True)
            self.label_search2.setVisible(True)
            self.label_search3.setVisible(True)
            self.label_search4.setVisible(True)
            self.label_search5.setVisible(True)
            self.label_search6.setVisible(True)
            self.label_result1.setVisible(True)
            self.label_result2.setVisible(True)
            self.label_result3.setVisible(True)
            self.label_result4.setVisible(True)
            self.label_result5.setVisible(True)
            self.label_result6.setVisible(True)
            self.pushButton_next.setEnabled(True)

            try:
                fname = row[6]
                
                if fname != "":
                    pixmap = QtGui.QPixmap(fname)

                    if pixmap.isNull():
                        self.img_labelSearch.clear()
                        self.img_labelSearch.setText('Image too large to preview. Please see the image in: ' + fname)
                        self.img_labelSearch.resize(480,30)
                    
                    else:
                        self.img_labelSearch.clear()
                        pixmap = pixmap.scaled(480, 480, QtCore.Qt.AspectRatioMode.KeepAspectRatio)
                        self.img_labelSearch.setPixmap(pixmap)
                        self.img_labelSearch.setScaledContents(True)
                        self.img_labelSearch.resize(pixmap.width(),pixmap.height())
                    self.img_labelSearch.setVisible(True)
                    self.frame_search1.setVisible(True)
                    
            except Exception as e:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "An error has occurred, could not load the image." + '\nError code: ' + str(e), qm.StandardButton.Close, qm.StandardButton.Close)



    #Call query to search users
    def searchUser(self):
        item = self.comboBox.currentIndex()
        if item == 0:
            if self.lineEdit_filter.text().isdigit():
                self.showResults(data.searchUsers("id", self.lineEdit_filter.text(), self.radioButton.isChecked()))
            else:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "Please enter only digits for the ID number filter.", qm.StandardButton.Close, qm.StandardButton.Close)

        elif item == 1:
            if self.lineEdit_filter.text().replace(" ","").isalpha():
                self.showResults(data.searchUsers("names", self.lineEdit_filter.text(), self.radioButton.isChecked()))
            else:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "Please enter only alphabetic characters for the names filter.", qm.StandardButton.Close, qm.StandardButton.Close)
        
        elif item == 2:
            if self.lineEdit_filter.text().replace(" ","").isalpha():
                self.showResults(data.searchUsers("surnames", self.lineEdit_filter.text(), self.radioButton.isChecked()))
            else:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "Please enter only alphabetic characters for the surnames filter.", qm.StandardButton.Close, qm.StandardButton.Close)
        
        elif item == 3:
            if self.lineEdit_filter.text().replace(" ","").isalpha():
                self.showResults(data.searchUsers("gender", self.lineEdit_filter.text(), self.radioButton.isChecked()))
            else:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "Please enter only alphabetic characters for the gender filter.", qm.StandardButton.Close, qm.StandardButton.Close)
        
        elif item == 4:
            if self.lineEdit_filter.text().replace(" ","").isalpha():
                self.showResults(data.searchUsers("nationality", self.lineEdit_filter.text(), self.radioButton.isChecked()))
            else:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "Please enter only alphabetic characters for the nationality filter.", qm.StandardButton.Close, qm.StandardButton.Close)

        elif item == 5:
            if self.lineEdit_filter.text().replace(" ","").isalnum():
                self.showResults(data.searchUsers("dob", self.lineEdit_filter.text(), self.radioButton.isChecked()))
            else:
                qm = QtWidgets.QMessageBox
                qm.critical(self.centralwidget,"Error", "Please enter only alphanumeric characters for the date of birth filter.", qm.StandardButton.Close, qm.StandardButton.Close)
    
    #Function to change the confidence level
    def changeCI(self):
        text, ok = QtWidgets.QInputDialog.getText(self.centralwidget, 'Settings',    'The confidence level by default is 90%. Enter the new confidence level (only numbers):')
        if ok and text.isdigit():
            core.minCI = int(text)

    def format(self):
        item = self.comboBox.currentIndex()
        if item == 5:
            self.label_format.setVisible(True)
        else:
            self.label_format.setVisible(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
