# Form implementation generated from reading ui file 'Proyecto2.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
import core
import numpy as np
from time import sleep
from PIL import Image, ImageQt

class Ui_MainWindow(object):

    pathImage = ''
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 618)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setVisible(False)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 1001, 591))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 35, 490, 550))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(2, 30, 486, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.img_label = QtWidgets.QLabel(self.frame)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(350, 512, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.processImage)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setGeometry(QtCore.QRect(500, 35, 490, 550))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 471, 481))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.formLayout.setContentsMargins(15, 45, 15, 0)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_6)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 510, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")


        #Creating home page
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1010, 600))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
       
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(118, 280, 180, 180))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(((os.path.dirname(os.path.realpath(__file__))+"\\resources\\OCRicon.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.showMainPage)
        self.pushButton_3.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(415, 280, 180, 180))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(((os.path.dirname(os.path.realpath(__file__))+"\\resources\\searchIcon.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(712, 280, 180, 180))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(((os.path.dirname(os.path.realpath(__file__))+"\\resources\\helpIcon.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        #Adding background
        self.label_Background = QtWidgets.QLabel(self.frame_3)
        self.label_Background.setGeometry(QtCore.QRect(0, 0, 1010, 600))
        self.label_Background.setText("")
        self.label_Background.setPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\homePage.png")))
        self.label_Background.setObjectName("label_Background")
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        #Creating top bar
        self.pushButton_New = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_New.setGeometry(QtCore.QRect(50, 0, 40, 40))
        self.pushButton_New.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\newIcon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_New.setIcon(icon)
        self.pushButton_New.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_New.setObjectName("pushButton_New")
        self.pushButton_New.setVisible(False)
        self.pushButton_New.clicked.connect(self.newImage)
        self.pushButton_New.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        self.pushButton_Home = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Home.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.pushButton_Home.setText("")
        self.pushButton_Home.clicked.connect(self.showHomePage)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\homeIcon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Home.setIcon(icon1)
        self.pushButton_Home.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton_Home.setVisible(False)
        self.pushButton_Home.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        self.pushButton_Help2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Help2.setGeometry(QtCore.QRect(970, 0, 40, 40))
        self.pushButton_Help2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\infoIcon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Help2.setIcon(icon2)
        self.pushButton_Help2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Help2.setObjectName("pushButton_Help2")
        self.pushButton_Help2.setVisible(False)
        self.pushButton_Help2.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")
        self.pushButton_Settings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Settings.setGeometry(QtCore.QRect(920, 0, 40, 40))
        self.pushButton_Settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap((os.path.dirname(os.path.realpath(__file__))+"\\resources\\settingsIcon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Settings.setIcon(icon2)
        self.pushButton_Settings.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.pushButton_Settings.setVisible(False)
        self.pushButton_Settings.setStyleSheet("QPushButton{background-color : transparent;} QPushButton::hover" "{" "background-color : rgb(229, 241, 251);""}")

        

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtGui.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSearch_info = QtGui.QAction(MainWindow)
        self.actionSearch_info.setObjectName("actionSearch_info")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ID Reader"))
        self.groupBox.setTitle(_translate("MainWindow", "Image"))
        self.pushButton.setText(_translate("MainWindow", "Process Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Data extracted"))
        self.label.setText(_translate("MainWindow", "ID Number:"))
        self.label_2.setText(_translate("MainWindow", "Names:"))
        self.label_3.setText(_translate("MainWindow", "Family Names:"))
        self.label_4.setText(_translate("MainWindow", "Gender:"))
        self.label_5.setText(_translate("MainWindow", "Nationality:"))
        self.label_6.setText(_translate("MainWindow", "Date of Birth:"))
        self.pushButton_2.setText(_translate("MainWindow", "Save Data"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open image"))
        self.actionSearch_info.setText(_translate("MainWindow", "Search info"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open image"))
        self.actionSearch_info.setText(_translate("MainWindow", "Search info"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


    #Function to show the main page
    def showMainPage(self):
        self.frame_3.setVisible(False)
        self.frame_2.setVisible(True)
        self.frame.setVisible(True)
        self.img_label.setVisible(True)
        self.pushButton_Help2.setVisible(True)
        self.pushButton_Home.setVisible(True)
        self.pushButton_New.setVisible(True)
        self.pushButton_Settings.setVisible(True)

    #Function to open a file
    def getfile(self):
        try:
            fDialog = QtWidgets.QFileDialog()
            file_filter = 'Image File (*.jpg *.jpeg *.png)'
            fname = fDialog.getOpenFileName(caption='Select a data file', filter=file_filter,)
            if fname[0] != "":
                self.frame_3.setVisible(False)
                
                self.pathImage = fname[0]
                pixmap = QtGui.QPixmap(self.pathImage)

                if pixmap.isNull():
                    self.img_label.clear()
                    self.img_label.setText('Image too large to preview. Please proceed to process the image.')
                    
                else:
                    self.img_label.clear()
                    pixmap = pixmap.scaled(480, 480, QtCore.Qt.AspectRatioMode.KeepAspectRatio)
                    self.img_label.setPixmap(pixmap)
                    self.img_label.setScaledContents(True)
                    self.img_label.resize(pixmap.width(),pixmap.height())
                self.showMainPage()
        except Exception as e:
            print('Error ',e)
    
    #Function to process the image
    def processImage(self):
        print(self.pathImage)
        #Initialze QtGui.QImage() with arguments data, height, width, and QImage.Format
        imgResults = core.processImage(self.pathImage)
        
        #Review if the process finished
        if imgResults[0]:
            pixmap = QtGui.QPixmap(imgResults[1])
            pixmap = pixmap.scaled(480, 480, QtCore.Qt.AspectRatioMode.KeepAspectRatio)
            self.img_label.setPixmap(pixmap)
            self.img_label.setScaledContents(True)
            self.img_label.resize(pixmap.width(),pixmap.height())

            self.lineEdit.setText(imgResults[2][0][1])
            if imgResults[2][0][2] < core.minCI:
                self.lineEdit.setStyleSheet("color: red;")

            self.lineEdit_2.setText(imgResults[2][1][1])
            if imgResults[2][1][2] < core.minCI:
                self.lineEdit_2.setStyleSheet("color: red;")

            self.lineEdit_3.setText(imgResults[2][2][1])
            if imgResults[2][2][2] < core.minCI:
                self.lineEdit_3.setStyleSheet("color: red;")

            self.lineEdit_4.setText(imgResults[2][3][1])
            if imgResults[2][3][2] < core.minCI:
                self.lineEdit_4.setStyleSheet("color: red;")

            self.lineEdit_5.setText(imgResults[2][4][1])
            if imgResults[2][4][2] < core.minCI:
                self.lineEdit_5.setStyleSheet("color: red;")

            self.lineEdit_6.setText(imgResults[2][5][1])
            if imgResults[2][5][2] < core.minCI:
                self.lineEdit_6.setStyleSheet("color: red;")

            self.frame_2.setVisible(True)
            print('Process finished ', imgResults[0])
        else:
            print(imgResults[1])
        
    #Function to get back home page
    def showHomePage(self):
        self.frame_3.setVisible(True)
        self.frame_2.setVisible(False)
        self.pushButton_Help2.setVisible(False)
        self.pushButton_Home.setVisible(False)
        self.pushButton_New.setVisible(False)
        self.pathImage = ''
        self.img_label.clear()
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        core.results = []
        core.processFinish = False

    #Function to open a new image
    def newImage(self):
        if self.pathImage != '':
            qm = QtWidgets.QMessageBox
            ans = qm.question(self.centralwidget,"Warning", "When open a new image data not saved will be lost. Are you sure to continue?", qm.StandardButton.Yes | qm.StandardButton.No, qm.StandardButton.No)

            if ans == qm.StandardButton.Yes:
                self.pathImage = ''
                self.img_label.clear()
                self.lineEdit.clear()
                self.lineEdit_2.clear()
                self.lineEdit_3.clear()
                self.lineEdit_4.clear()
                self.lineEdit_5.clear()
                self.lineEdit_6.clear()
                core.results = []
                core.processFinish = False
                self.getfile()
        else:
            self.getfile()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
